In [58]:
!python train.py

Loading cora dataset...
FINISHED LOADING DATA


In [19]:
from utils import load_data, accuracy
adj, features, labels, idx_train, idx_val, idx_test = load_data()


Loading cora dataset...


In [20]:
adj

tensor([[0.1667, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.2000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.2000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2500]])

In [47]:
import numpy as np
x = np.load('newgraph.npy')
x = (x + np.eye(len(x))) > 0
x = x / np.sum(x, axis=1)

In [48]:
adj

tensor([[0.1667, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.2000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.2000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2500]])

In [49]:
x

array([[0.14285714, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.16666667, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.25      , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.14285714,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.16666667]])

In [50]:
from scipy.stats import describe

describe(adj), describe(x)

(DescribeResult(nobs=2708, minmax=(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), array([0.18257418, 0.5       , 0.2       , ..., 0.2581989 , 0.31622776,
        0.35355338], dtype=float32)), mean=array([0.00032929, 0.0002308 , 0.00024343, ..., 0.0003894 , 0.00038289,
        0.00039777], dtype=float32), variance=array([5.1196195e-05, 9.8078286e-05, 3.8920065e-05, ..., 8.4401909e-05,
        8.4994812e-05, 1.1066525e-04], dtype=float32), skewness=array([22.427404, 48.22218 , 28.009035, ..., 24.120283, 25.982422,
        27.379131], dtype=float32), kurtosis=array([ 512.8776 , 2402.959  ,  813.34955, ...,  591.45996,  726.42633,
         775.518  ], dtype=float32)),
 DescribeResult(nobs=2708, minmax=(array([0., 0., 0., ..., 0., 0., 0.]), array([0.14285714, 0.16666667, 0.25      , ..., 1.        , 0.14285714,
        0.16666667])), mean=array([0.00036928, 0.00036928, 0.00036928, ..., 0.00036928, 0.00036928,
        0.00036928]), variance=array([5.26368181e-05, 6.14323570e-05, 9.2216

In [53]:
adj.sum(dim=1), adj.sum(dim=0)

(tensor([0.8917, 0.6250, 0.6592,  ..., 1.0545, 1.0369, 1.0772]),
 tensor([0.8917, 0.6250, 0.6592,  ..., 1.0545, 1.0369, 1.0772]))