In [1]:
for i in range(300,350):
    print('i)

300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349


In [1]:
from __future__ import division
from __future__ import print_function

import os
import glob
import time
import random
import argparse
import scipy.sparse as sp
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
import pdb

from utils import load_data, accuracy, normalize_adj
from models import GAT, SpGAT

random.seed(72)
np.random.seed(72)
torch.manual_seed(72)
torch.cuda.manual_seed(72)

# Load data
adj, features, labels, idx_train, idx_val, idx_test = load_data()

# Model and optimizer
model = GAT(nfeat=features.shape[1], 
            nhid=8, 
            nclass=7, 
            dropout=0.6, 
            nheads=8, 
            alpha=0.2)

if True:
    model.cuda()
    features = features.cuda()
    adj = adj.cuda()
    labels = labels.cuda()
    idx_train = idx_train.cuda()
    idx_val = idx_val.cuda()
    idx_test = idx_test.cuda()

features, adj, labels = Variable(features), Variable(adj), Variable(labels)

def compute_test():
    model.eval()
    output, _ = model(features, adj)
    print(output)
    loss_test = F.nll_loss(output[idx_test], labels[idx_test])
    acc_test = accuracy(output[idx_test], labels[idx_test])
    print("Test set results:",
          "loss= {:.4f}".format(loss_test.data[0]),
          "accuracy= {:.4f}".format(acc_test.data[0]))

# Train model
model.load_state_dict(torch.load('357.pkl'))

# Testing
compute_test()


Loading cora dataset...
[[0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0]]


FileNotFoundError: [Errno 2] No such file or directory: '357.pkl'

In [1]:
from __future__ import division
from __future__ import print_function

import os
import glob
import time
import random
import argparse
import scipy.sparse as sp
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
import pdb

from utils import load_data, accuracy, normalize_adj
from models import GAT, SpGAT

# Load data
adj, features, labels, idx_train, idx_val, idx_test = load_data()

import torch


model = torch.load('model.pth')


model.cuda()
features = features.cuda()
adj = adj.cuda()
labels = labels.cuda()
idx_train = idx_train.cuda()
idx_val = idx_val.cuda()
idx_test = idx_test.cuda()
    
model.eval()
output, _ = model(features, adj)
print(output)
loss_test = F.nll_loss(output[idx_test], labels[idx_test])
acc_test = accuracy(output[idx_test], labels[idx_test])
print("Test set results:",
      "loss= {:.4f}".format(loss_test.data[0]),
      "accuracy= {:.4f}".format(acc_test.data[0]))


Loading cora dataset...


/anaconda/envs/py3/lib/python3.6/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'layers.VariationalAttentionNet' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)


mu tensor([[-0.0080],
        [ 0.0010],
        [-0.0019],
        ...,
        [-0.0024],
        [-0.0008],
        [-0.0012]], device='cuda:0', grad_fn=<ThAddmmBackward>)
var tensor([[0.9804],
        [0.9894],
        [0.9837],
        ...,
        [0.9910],
        [0.9825],
        [0.9847]], device='cuda:0', grad_fn=<SoftplusBackward>)
mu tensor([[-0.0243],
        [-0.0245],
        [-0.0256],
        ...,
        [-0.0204],
        [-0.0196],
        [-0.0223]], device='cuda:0', grad_fn=<ThAddmmBackward>)
var tensor([[0.9999],
        [0.9938],
        [0.9840],
        ...,
        [1.0028],
        [1.0048],
        [1.0022]], device='cuda:0', grad_fn=<SoftplusBackward>)
mu tensor([[-0.0129],
        [-0.0134],
        [-0.0124],
        ...,
        [-0.0114],
        [-0.0120],
        [-0.0145]], device='cuda:0', grad_fn=<ThAddmmBackward>)
var tensor([[0.9959],
        [1.0021],
        [0.9981],
        ...,
        [1.0142],
        [1.0062],
        [1.0027]], device=

/anaconda/envs/py3/lib/python3.6/site-packages/ipykernel_launcher.py:44: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
/anaconda/envs/py3/lib/python3.6/site-packages/ipykernel_launcher.py:45: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


In [9]:
model.attention_0.att.lin21()

RuntimeError: size mismatch, m1: [2708 x 4141], m2: [16 x 16] at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/THC/generic/THCTensorMathBlas.cu:249

In [4]:
model.

(tensor([5, 3, 6, 6, 1, 1, 0, 5, 5, 0, 5, 2, 1, 4, 5, 5, 6, 5, 5, 5], device='cuda:0'),
 tensor([5, 3, 6, 6, 1, 1, 0, 5, 5, 0, 5, 2, 1, 4, 5, 5, 6, 5, 5, 5], device='cuda:0'))